### ISSUE TITLE
Jake: Updating draw.io package

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstormports/community-project#1]
Currently, I have a "it runs" branch at https://github.com/ocdtrekkie/drawio/tree/sandstorm and I have the packaging key.

The biggest issue here is to stage.sh (https://github.com/ocdtrekkie/drawio/blob/c9bbab5c11eaf879ff473e63533cfbaeaa043062/etc/sandstorm/stage.sh) explicitly copies files to use in the Sandstorm package... some of them I had to comment out, which means those features are renamed or moved. And a lot of new files *aren't* copied, so it's likely the package has a lot of holes I need to audit and test.

**Comment by ocdtrekkie** [comment]
This is definitely my next Sandstorm priority (helping get the updated TTRSS shipped was ahead of it), but I am trying to complete some certifications before the end of this month which is my focus right now.

**Comment by zenhack** [comment]
Best of luck!
